### PR TITLE
Header

### PR DESCRIPTION
**Pull request by ashkanx**

### CODE REVIEW

**Comment by sash-257defi** [comment]
https://github.com/ashkanx-champion/binary-style/blob/6cd4bb7924e17f9a6d9008ba65a507f0782de171/_sass/all.scss

**Comment by sash-257defi** [comment]
import url(https://fonts.googleapis.com/css?family=Roboto:300,400,700&subset=latin,vietnamese,cyrillic-ext,latin-ext,cyrillic);

**Comment by sash-257defi** [comment]
Should be Noto

import url('https://fonts.googleapis.com/css?family=Noto+Sans:400,700&subset=cyrillic-ext,devanagari,vietnamese');

**Comment by ashkanx** [comment]
I don't know why this keeps happening every time I merge binary-style to champion-fx

**Pull request merged**
